## Numpy and Pandas

In [1]:
import pandas as pd

In [2]:
pd.__version__

'1.1.2'

In [3]:
import numpy as np

In [4]:
np.sign(5)

1

In [5]:
np.__version__

'1.18.1'

In [8]:
mass = [12,20,32]

In [9]:
volume = [36, 18, 10]

In [10]:
mass_array = np.array(mass)

In [13]:
volume_array = np.array(volume)

In [14]:
density = mass_array/volume_array

In [15]:
density

array([0.33333333, 1.11111111, 3.2       ])

### Numpy arrays can only have one data type

In [18]:
massvolume = [[12,20,32],[36,18,10]]

In [19]:
massvolume

[[12, 20, 32], [36, 18, 10]]

In [20]:
massvolume_array = np.array(massvolume)

In [21]:
massvolume_array

array([[12, 20, 32],
       [36, 18, 10]])

In [22]:
print(massvolume_array)

[[12 20 32]
 [36 18 10]]


In [24]:
massvolume_array.shape

(2, 3)

In [25]:
massvolume_array[1,2]

10

In [30]:
massvolume_array[0:2, 0:3]

array([[12, 20, 32],
       [36, 18, 10]])

Looping over a 2 D numpy array

In [31]:
for mass in mass_array:
    weight = mass * 9.8
    print(weight)

117.60000000000001
196.0
313.6


In [32]:
massvolume

[[12, 20, 32], [36, 18, 10]]

In [33]:
massvolume_array

array([[12, 20, 32],
       [36, 18, 10]])

np.nditer function

In [34]:
for value in np.nditer(massvolume_array):
    print(value)

12
20
32
36
18
10


In [36]:
for value in np.nditer(massvolume_array[0]):
    weight = value * 9.8
    print(weight)

117.60000000000001
196.0
313.6


In [37]:
from numpy import array

In [40]:
list1 = [3,6,2,7,8]

In [41]:
array_1 = np.array(list1)

In [42]:
print(array_1)

[3 6 2 7 8]
